#ifndef ARIADNE_CONFIG_H
#define ARIADNE_CONFIG_H

#cmakedefine SIZEOF_CHAR @SIZEOF_CHAR@
#cmakedefine SIZEOF_SHORT_INT @SIZEOF_SHORT_INT@
#cmakedefine SIZEOF_INT @SIZEOF_INT@
#cmakedefine SIZEOF_LONG_INT @SIZEOF_LONG_INT@
#cmakedefine SIZEOF_LONG_LONG_INT @SIZEOF_LONG_LONG_INT@
#cmakedefine SIZEOF_FLOAT @SIZEOF_FLOAT@
#cmakedefine SIZEOF_DOUBLE @SIZEOF_DOUBLE@
#cmakedefine SIZEOF_LONG_DOUBLE @SIZEOF_LONG_DOUBLE@

#cmakedefine HAVE_GMPXX_H
#cmakedefine HAVE_CAIRO_H
#cmakedefine HAVE_GTK2_H

#cmakedefine HAVE_LIBBOOST_SERIALIZATION_HPP
#cmakedefine ARIADNE_ENABLE_SERIALIZATION

#endif /* ARIADNE_CONFIG_H */
