#ifndef ARIADNE_CONFIG_H
#define ARIADNE_CONFIG_H

#cmakedefine SIZEOF_INT @SIZEOF_INT@
#cmakedefine HAVE_GMPXX_H
#cmakedefine HAVE_CAIRO_H

#cmakedefine HAVE_LIBBOOST_SERIALIZATION
#cmakedefine ARIADNE_ENABLE_SERIALIZATION

#endif /* ARIADNE_CONFIG_H */
