#ifndef ARIADNE_CONFIG_HPP
#define ARIADNE_CONFIG_HPP

#cmakedefine SIZEOF_CHAR @SIZEOF_CHAR@
#cmakedefine SIZEOF_SHORT_INT @SIZEOF_SHORT_INT@
#cmakedefine SIZEOF_INT @SIZEOF_INT@
#cmakedefine SIZEOF_LONG_INT @SIZEOF_LONG_INT@
#cmakedefine SIZEOF_LONG_LONG_INT @SIZEOF_LONG_LONG_INT@
#cmakedefine SIZEOF_FLOAT @SIZEOF_FLOAT@
#cmakedefine SIZEOF_DOUBLE @SIZEOF_DOUBLE@
#cmakedefine SIZEOF_LONG_DOUBLE @SIZEOF_LONG_DOUBLE@

#cmakedefine ARIADNE_ENABLE_STACK_TRACE

#cmakedefine HAVE_YAML_H
#cmakedefine HAVE_CAIRO_H
#cmakedefine HAVE_GNUPLOT_H

#endif /* ARIADNE_CONFIG_HPP */
