name: Debug

on:
  push:
    branches:
      - master
  pull_request:

env:
  BUILD_TYPE: Debug

jobs:
  build:

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "macOS 12 AppleClang 14 [Debug]",
            os: macos-12,
            cxx-cmd: "clang++"
          }
          - {
            name: "macOS 12 GCC 11 [Debug]",
            os: macos-12,
            cxx-pkg: "gcc@11",
            cxx-cmd: "g++-11"
          }
          - {
            name: "Ubuntu 22.04 Clang 14 [Debug]",
            os: ubuntu-22.04,
            cxx-pkg: "clang-14",
            cxx-cmd: "clang++-14"
          }
          - {
            name: "Ubuntu 22.04 GCC 11 [Debug]",
            os: ubuntu-22.04,
            cxx-pkg: "g++-11",
            cxx-cmd: "g++-11"
          }

    steps:
    - uses: actions/checkout@v3

    - name: Get macOS Concurrency
      if: runner.os == 'macOS'
      run: |
        echo NPROC="sysctl -n hw.ncpu" >> $GITHUB_ENV
        echo "Running on $(sysctl -n hw.ncpu) threads ..."

    - name: Get Linux Concurrency
      if: runner.os == 'Linux'
      run: |
        echo NPROC="nproc" >> $GITHUB_ENV
        echo "Running on $(nproc) threads ..."

    - name: Set Up macOS Dependencies
      if: runner.os == 'macOS'
      run: |
        brew install ninja ${{matrix.config.cxx-pkg}} python3 mpfr cairo gnuplot
        export PKG_CONFIG_PATH=/usr/local/opt/libffi/lib/pkgconfig
        sudo easy_install pip
        sudo pip3 install --upgrade pip
        sudo pip3 install pytest

    - name: Set Up Linux Dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt install -y cmake ninja-build pkg-config ${{matrix.config.cxx-pkg}} libcairo2-dev gnuplot libmpfr-dev python3-pip python3-dev
        sudo pip3 install pytest

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_CXX_COMPILER=${{matrix.config.cxx-cmd}} -G "Ninja" -DWERROR=ON

    - name: Build Library and Bindings
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --parallel $($NPROC)

    - name: Build Tests
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --parallel $($NPROC) --target tests

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: ctest -j $($NPROC) --output-on-failure